#!/usr/bin/env python3
"""Author the lightweight Challenger-2-inspired tank OBJ using only Python 3.

Coordinates: +Y up, +Z forward, origin on ground below the turret pivot.
This writes a real, editable mesh asset, not runtime procedural geometry.
Dimensions deliberately retain the original game's footprint, not SI scale.
"""

import argparse
import math
from pathlib import Path

# Landmarks measured from the user's 600x190 side elevation. The hull spans
# image X=156..554; retain the existing 4.48-unit gameplay hull length.
PROFILE_SCALE = 4.48 / (554 - 156)
# Small lift requested after the isometric detail pass; keep the complete
# turret/gun assembly together and extend its mounting ring down to the hull.
TURRET_RISE = .08


def profile(px, py):
    """Image right is vehicle rear; image Y=181 is the ground line."""
    return ((181-py)*PROFILE_SCALE, (341-px)*PROFILE_SCALE)


class Model:
    def __init__(self):
        self.lines = ["# Generated by tools/generate_tank_model.py", "mtllib challenger2.mtl"]
        self.count = 0
        self.triangles = 0
        self.objects = []

    def mesh(self, name, material, vertices, faces):
        if material in ("Turret", "TurretDark", "Barrel") and name != "turret_ring":
            vertices = [(x,y+TURRET_RISE,z) for x,y,z in vertices]
        self.objects.append((name, material, vertices, faces))
        self.lines += [f"o {name}", f"usemtl {material}", "s off"]
        self.lines += ["v " + " ".join(f"{v:.6f}" for v in p) for p in vertices]
        for face in faces:
            # Explicit triangles keep triangulation reproducible across editors.
            for i in range(1, len(face) - 1):
                self.lines.append("f " + " ".join(str(self.count + j + 1)
                                                   for j in (face[0], face[i], face[i + 1])))
                self.triangles += 1
        self.count += len(vertices)

    def solid(self, name, material, vertices, faces):
        """Orient a convex solid's faces away from its centre."""
        centre = [sum(p[i] for p in vertices) / len(vertices) for i in range(3)]
        oriented = []
        for face in faces:
            a, b, c = (vertices[i] for i in face[:3])
            u, v = ([b[i] - a[i] for i in range(3)], [c[i] - a[i] for i in range(3)])
            n = (u[1]*v[2]-u[2]*v[1], u[2]*v[0]-u[0]*v[2], u[0]*v[1]-u[1]*v[0])
            oriented.append(face if sum(n[i]*(a[i]-centre[i]) for i in range(3)) > 0
                            else list(reversed(face)))
        self.mesh(name, material, vertices, oriented)

    def loft(self, name, material, rings):
        n = len(rings[0])
        faces = [list(range(n)), list(range((len(rings)-1)*n, len(rings)*n))]
        for r in range(len(rings)-1):
            faces += [[r*n+i, r*n+(i+1)%n, (r+1)*n+(i+1)%n, (r+1)*n+i]
                      for i in range(n)]
        self.solid(name, material, [p for ring in rings for p in ring], faces)

    def box(self, name, material, low, high):
        x, y, z = low
        X, Y, Z = high
        self.loft(name, material, [[(x,y,z),(X,y,z),(X,y,Z),(x,y,Z)],
                                   [(x,Y,z),(X,Y,z),(X,Y,Z),(x,Y,Z)]])

    def cylinder(self, name, material, centre, radius, length, axis=0, sides=24):
        axes = [i for i in range(3) if i != axis]
        rings = []
        for offset in (-length/2, length/2):
            ring = []
            for i in range(sides):
                p = list(centre)
                p[axis] += offset
                p[axes[0]] += radius * math.cos(i*math.tau/sides)
                p[axes[1]] += radius * math.sin(i*math.tau/sides)
                ring.append(tuple(p))
            rings.append(ring)
        self.loft(name, material, rings)

    def side_prism(self, name, material, points, half_width):
        """Extrude a convex, measured side silhouette across the vehicle."""
        self.loft(name, material,
                  [[(x, *profile(px,py)) for px,py in points]
                   for x in (-half_width, half_width)])

    def tube(self, name, material, centre, radius, length, direction, sides=12):
        """Closed low-poly cylinder along an arbitrary direction."""
        mag = math.sqrt(sum(v*v for v in direction))
        d = [v/mag for v in direction]
        u = [d[2],0,-d[0]]
        mag = math.hypot(u[0],u[2])
        u = [v/mag for v in u]
        v = [d[1]*u[2],d[2]*u[0]-d[0]*u[2],-d[1]*u[0]]
        self.loft(name,material,
                  [[tuple(centre[k]+offset*d[k]+radius*(u[k]*math.cos(i*math.tau/sides)+
                           v[k]*math.sin(i*math.tau/sides)) for k in range(3))
                    for i in range(sides)] for offset in (-length/2,length/2)])


def outline(width, rear, front, chamfer, y):
    return [(-width+chamfer,y,rear), (width-chamfer,y,rear),
            (width,y,rear+chamfer), (width,y,front-chamfer),
            (width-chamfer,y,front), (-width+chamfer,y,front),
            (-width,y,front-chamfer), (-width,y,rear+chamfer)]


def roof_height(x, z):
    """Follow the existing turret's longitudinal roof facets exactly."""
    sections = [profile(px, py) for px, py in ((222,98),(289,62),(365,57),(466,68))]
    for (y0,z0),(y1,z1) in zip(sections,sections[1:]):
        if z >= z1:
            return y0+(y1-y0)*(z-z0)/(z1-z0)
    return sections[-1][0]


def hull_height(x, z):
    sections = [(profile(px,top)[0],profile(px,side)[0],profile(px,top)[1])
                for px,side,top in ((156,135,132),(174,128,119),(241,124,104),
                                    (414,121,96),(554,117,94))]
    shoulder = max(0,min(1,(abs(x)-.77)/.29))
    for (top0,side0,z0),(top1,side1,z1) in zip(sections,sections[1:]):
        if z >= z1:
            t = (z-z0)/(z1-z0)
            top,side = top0+(top1-top0)*t,side0+(side1-side0)*t
            return top+(side-top)*shoulder
    top,side,_ = sections[-1]
    return top+(side-top)*shoulder


def surface_plate(m, name, material, points, surface, offset=.003, thickness=.008):
    """A shallow convex fitting seated on a sloped armour/deck surface."""
    m.loft(name, material, [[(x,surface(x,z)+h,z) for x,z in points]
                           for h in (offset,offset+thickness)])


def roof_rect(m, name, material, x0, z0, x1, z1, offset=.003, thickness=.008):
    surface_plate(m,name,material,[(x0,z0),(x1,z0),(x1,z1),(x0,z1)],
                  roof_height,offset,thickness)


def rod(m, name, material, start, end, radius=.008, sides=8):
    direction = [end[i]-start[i] for i in range(3)]
    m.tube(name,material,tuple((start[i]+end[i])/2 for i in range(3)),radius,
           math.sqrt(sum(v*v for v in direction)),direction,sides)


def roof_details(m):
    # Thin overlapping plates and their exposed fasteners follow the glacis
    # facet. Their footprint stays inside the approved armour cross-sections.
    surface_plate(m,"gun_roof_applique","Turret",
                  [(-.27,.62),(.21,.62),(.18,1.13),(-.22,1.13)],roof_height)
    for side in (-1,1):
        x = side*.255
        rod(m,f"roof_applique_seam_{side}","TurretDark",
            (x,roof_height(x,.64)+.014,.64),
            (x*.80,roof_height(x,1.10)+.014,1.10),.006)
        for i in range(5):
            z = .67+i*.095
            xx = x*(1-(z-.64)*.20/.46)
            m.cylinder(f"roof_applique_bolt_{side}_{i}","Turret",
                       (xx,roof_height(xx,z)+.024,z),.011,.010,axis=1,sides=6)
        # Long shallow score lines on the shoulder beside the central plate.
        for i in range(2):
            x0 = side*(.33+i*.14)
            rod(m,f"roof_shoulder_seam_{side}_{i}","TurretDark",
                (x0,roof_height(x0,.65)+.005,.65),
                (x0,roof_height(x0,.92)+.005,.92),.004,sides=6)

    # Recessed hatch surround with a chamfered lid and transverse hinges.
    hatch = [(.28,-.28),(.56,-.28),(.62,-.22),(.62,.06),
             (.56,.12),(.28,.12),(.22,.06),(.22,-.22)]
    surface_plate(m,"loader_hatch_gasket","TurretDark",hatch,roof_height)
    lid = [(.42+(x-.42)*.91,-.08+(z+.08)*.91) for x,z in hatch]
    surface_plate(m,"loader_hatch","Turret",lid,roof_height,.012,.013)
    for x in (.30,.54):
        y = roof_height(x,-.29)+.026
        m.cylinder(f"loader_hinge_{x}","Turret",(x,y,-.29),.024,.075,sides=12)
    y = roof_height(.42,.025)+.031
    for x in (.36,.48):
        m.box(f"loader_handle_foot_{x}","Turret",(x-.012,y-.01,.01),(x+.012,y+.024,.04))
    rod(m,"loader_hatch_handle","TurretDark",(.36,y+.024,.025),(.48,y+.024,.025),.009)
    # Cupola lid hinge, handle and a thin concentric rim inside its silhouette.
    m.cylinder("commander_lid_rim","TurretDark",(-.33,1.489,-.12),.166,.005,axis=1)
    m.cylinder("commander_lid_inset","Turret",(-.33,1.493,-.12),.152,.007,axis=1)
    m.cylinder("commander_hinge","Turret",(-.33,1.49,-.30),.023,.17,sides=12)
    rod(m,"commander_grab_handle","Turret",(-.40,1.515,-.04),(-.28,1.515,-.04),.011)

    # Service covers used to be horizontal boxes partly buried in this facet.
    for side in (-1,1):
        x = side*.43
        roof_rect(m,f"roof_access_gasket_{side}","TurretDark",x-.17,-1.08,x+.17,-.58)
        roof_rect(m,f"roof_access_panel_{side}","Turret",x-.16,-1.07,x+.16,-.59,.011)
        for z in (-1.01,-.65):
            roof_rect(m,f"roof_hinge_{side}_{z}","Turret",x-.18,z-.025,x-.12,z+.025,.020,.013)
        for z in (-1.16,-.48):
            # U-shaped tie-downs have a real gap beneath the crossbar.
            for dx in (-.038,.038):
                roof_rect(m,f"roof_tie_foot_{side}_{z}_{dx}","Turret",x+dx-.009,z-.012,
                          x+dx+.009,z+.012,.003,.025)
            y = roof_height(x,z)+.030
            rod(m,f"roof_tie_bar_{side}_{z}","Turret",(x-.038,y,z),(x+.038,y,z),.007)
    # Small circular filler cap forward of the loader's hatch.
    y = roof_height(.57,.43)
    m.cylinder("roof_filler_seal","TurretDark",(.57,y+.011,.43),.050,.014,axis=1,sides=16)
    m.cylinder("roof_filler_cap","Turret",(.57,y+.019,.43),.037,.014,axis=1,sides=16)


def track(model, side):
    # A convex wrap of the wheel envelopes gives a flat contact run, sloped
    # approaches and small elevated end turns, rather than a stadium capsule.
    road_centres = [profile(px,157) for px in (227,275,324,373,423,470)]
    end_centres = [profile(180,141), profile(511,140)]
    samples = []
    for (y,z),r in [(p,.262) for p in road_centres] + [(p,.226) for p in end_centres]:
        samples += [(z+r*math.cos(i*math.tau/24), y+r*math.sin(i*math.tau/24))
                    for i in range(24)]
    def cross(a,b,c):
        return (b[0]-a[0])*(c[1]-a[1])-(b[1]-a[1])*(c[0]-a[0])
    samples = sorted(set(samples))
    lower, upper = [], []
    for chain, ordered in ((lower,samples),(upper,reversed(samples))):
        for point in ordered:
            while len(chain) >= 2 and cross(chain[-2],chain[-1],point) <= 0:
                chain.pop()
            chain.append(point)
    path = lower[:-1] + upper[:-1]  # CCW in Z/Y; outward normals below.
    points = []
    for i,(z,y) in enumerate(path):
        prev, nxt = path[i-1],path[(i+1)%len(path)]
        normals = []
        for a,b in ((prev,(z,y)),((z,y),nxt)):
            dz,dy = b[0]-a[0],b[1]-a[1]
            length = math.hypot(dz,dy)
            normals.append((-dz/length,dy/length))  # Y/Z order
        ny,nz = (normals[0][j]+normals[1][j] for j in range(2))
        length = math.hypot(ny,nz)
        points.append((y,z,ny/length,nz/length))
    vertices = []
    for x, inset in ((.765,0), (1.085,0), (.765,.038), (1.085,.038)):
        vertices += [(side*x, y-inset*ny, z-inset*nz) for y,z,ny,nz in points]
    n = len(points)
    faces = []
    for i in range(n):
        j = (i+1)%n
        faces += [[i,j,n+j,n+i], [2*n+i,3*n+i,3*n+j,2*n+j],
                  [i,2*n+i,2*n+j,j], [n+i,n+j,3*n+j,3*n+i]]
    # Mirroring across X also reverses winding.
    if side > 0:
        faces = [list(reversed(f)) for f in faces]
    label = "right" if side > 0 else "left"
    model.mesh(f"{label}_track_belt", "Tracks", vertices, faces)

    # Broad tread shoes around the full loop, not tiny high-frequency teeth.
    lengths = [math.hypot(points[(i+1)%n][0]-p[0],points[(i+1)%n][1]-p[1])
               for i,p in enumerate(points)]
    perimeter = sum(lengths)
    def sample(distance):
        for i,length in enumerate(lengths):
            if distance <= length or i == n-1:
                y,z = points[i][:2]
                Y,Z = points[(i+1)%n][:2]
                t = distance/length
                return y+(Y-y)*t,z+(Z-z)*t,-(Z-z)/length,(Y-y)/length
            distance -= length
    for i in range(64):
        y,z,ny,nz = sample((i+.5)*perimeter/64)
        verts = [(side*x, y+ny*r-nz*t, z+nz*r+ny*t)
                 for r in (-.006,.006) for x,t in ((.75,-.045),(1.10,-.045),(1.10,.045),(.75,.045))]
        model.solid(f"{label}_shoe_{i:02}", "Tracks", verts,
                    [[0,1,2,3],[4,5,6,7],[0,4,5,1],[1,5,6,2],[2,6,7,3],[3,7,4,0]])

    for i,(y,z) in enumerate(road_centres):
        # Rubber tire, recessed painted steel disc, and proud central hub.
        model.cylinder(f"{label}_road_wheel_{i+1}", "Tracks", (side*.925,y,z), .222,.29)
        model.cylinder(f"{label}_wheel_disc_{i+1}", "Base", (side*1.076,y,z), .181,.026)
        model.cylinder(f"{label}_wheel_hub_{i+1}", "Base", (side*1.098,y,z), .070,.026, sides=16)
    for kind,(y,z) in zip(("idler","sprocket"),end_centres):
        model.cylinder(f"{label}_{kind}", "Tracks", (side*.925,y,z), .187,.29)
        model.cylinder(f"{label}_{kind}_disc", "Base", (side*1.073,y,z), .145,.026)
        model.cylinder(f"{label}_{kind}_hub", "Base", (side*1.095,y,z), .065,.026, sides=16)


def build():
    m = Model()
    m.side_prism("lower_hull", "Base",
                 [(172,129),(532,119),(481,157),(206,157)],.72)
    # Different front/rear deck heights and a long shallow glacis.
    m.loft("upper_hull", "Base",
           [[(-1.06,*profile(px,side_y)),(1.06,*profile(px,side_y)),
             (.77,*profile(px,top_y)),(-.77,*profile(px,top_y))]
            for px,side_y,top_y in ((156,135,132),(174,128,119),(241,124,104),
                                   (414,121,96),(554,117,94))])
    for side in (-1,1):
        track(m, side)
        label = "right" if side > 0 else "left"
        skirt_sections = [(169,134,141),(196,118,155),(248,117,156),
                          (305,117,156),(366,116,156),(424,115,156),
                          (481,114,155),(538,113,125)]
        for i,(a,b) in enumerate(zip(skirt_sections,skirt_sections[1:])):
            px,top,bottom = a
            PX,TOP,BOTTOM = b
            # Small panel gaps, without exaggerated bright edge strips.
            m.loft(f"{label}_skirt_{i}", "Base",
                   [[(side*x,*profile(p,y)) for p,y in
                     ((px+.4,top),(PX-.4,TOP),(PX-.4,BOTTOM),(px+.4,bottom))]
                    for x in (1.06,1.111)])
        # Painted rear drums and fittings don't enlarge the main hull collider.
        drum_y,drum_z = profile(577,108)
        m.cylinder(f"{label}_rear_drum", "HullFittings", (side*.47,drum_y,drum_z),.207,.50)
        for x in (side*.34,side*.61):
            m.cylinder(f"{label}_drum_band_{x}", "Tracks",(x,drum_y,drum_z),.217,.035)
            m.box(f"{label}_drum_buckle_{x}", "HullFittings",
                  (x-.033,drum_y-.055,drum_z-.229),(x+.033,drum_y+.055,drum_z-.214))
        m.box(f"{label}_drum_mount", "HullFittings",(side*.47-.19,.51,-2.73),
              (side*.47+.19,.57,-2.20))
        # Front/rear mud flaps and transverse fenders cover the track tops.
        for end,z in (("front",1.85),("rear",-2.18)):
            m.box(f"{label}_{end}_fender", "Base",(side*.925-.18,.65,z-.18),
                  (side*.925+.18,.69,z+.18))
            m.box(f"{label}_{end}_mudflap", "Tracks",(side*.925-.18,.47,z-.02),
                  (side*.925+.18,.65,z+.02))
        # The frontal reference has paired lamps and tow eyes on the glacis.
        x = side*.51
        m.box(f"{label}_headlight_mount", "Base",(x-.075,.63,1.84),(x+.075,.74,1.94))
        m.cylinder(f"{label}_headlight_rim", "Tracks",(x,.69,1.96),.049,.038,axis=2,sides=16)
        m.cylinder(f"{label}_headlight_lens", "Base",(x,.69,1.982),.036,.012,axis=2,sides=16)
        m.box(f"{label}_front_tow_lug", "Base",(x-.04,.40,1.85),(x+.04,.49,1.99))
        m.cylinder(f"{label}_tow_eye", "Tracks",(x,.46,2.001),.027,.012,axis=2,sides=12)
        # Rear light clusters sit outboard of the drums.
        x = side*.90
        m.box(f"{label}_tail_light_housing", "HullFittings",(x-.13,.64,-2.43),(x+.13,.79,-2.34))
        for dx in (-.065,.065):
            m.box(f"{label}_tail_lens_{dx}", "Tracks",(x+dx-.046,.675,-2.448),(x+dx+.046,.742,-2.43))
    # Framed rear cooling banks: recessed dark beds, raised slats and hinges.
    m.box("engine_deck", "Base", (-.72,.94,-2.30),(.72,1.015,-1.51))
    # Top reference: two banks of grilles around a central service panel.
    for side in (-1,1):
        x = side*.44
        for bank,z in enumerate((-2.10,-1.73)):
            m.box(f"engine_grille_bed_{side}_{bank}", "Tracks",(x-.22,1.015,z-.145),(x+.22,1.024,z+.145))
            for i in range(10):
                zz = z-.13+i*.028
                m.box(f"engine_louvre_{side}_{bank}_{i}", "Base",(x-.21,1.025,zz),(x+.21,1.039,zz+.012))
            for dx in (-.225,.225):
                m.box(f"engine_grille_frame_side_{side}_{bank}_{dx}","HullFittings",
                      (x+dx-.009,1.022,z-.155),(x+dx+.009,1.047,z+.155))
            for dz in (-.15,.15):
                m.box(f"engine_grille_frame_end_{side}_{bank}_{dz}","HullFittings",
                      (x-.234,1.022,z+dz-.009),(x+.234,1.047,z+dz+.009))
            m.box(f"engine_grille_spine_{side}_{bank}","HullFittings",
                  (x-.009,1.038,z-.14),(x+.009,1.047,z+.14))
            for dz in (-.09,.09):
                m.cylinder(f"engine_grille_hinge_{side}_{bank}_{dz}","HullFittings",
                           (x-side*.24,1.041,z+dz),.019,.066,axis=2,sides=8)
    m.box("engine_service_panel", "Base",(-.15,1.016,-2.27),(.15,1.042,-1.53))
    m.box("engine_service_handle", "Tracks",(-.07,1.043,-1.93),(.07,1.060,-1.90))
    # Low rear fender tool bins and diagonal lid stiffeners remain inboard.
    for side in (-1,1):
        x = side*.87
        m.box(f"rear_deck_toolbox_{side}","HullFittings",(x-.11,.90,-2.24),(x+.11,1.005,-1.59))
        m.box(f"rear_deck_toolbox_lid_{side}","HullFittings",(x-.116,1.005,-2.25),(x+.116,1.018,-1.58))
        for z in (-2.19,-1.86):
            rod(m,f"toolbox_lid_brace_{side}_{z}","HullFittings",
                (x-.085,1.024,z),(x+.085,1.024,z+.23),.008)
        # A restrained tow cable follows the narrow exposed hull shoulder.
        cable_z = (1.20,profile(241,0)[1],profile(414,0)[1],-1.35)
        for i,(z0,z1) in enumerate(zip(cable_z,cable_z[1:])):
            x0 = side*.94
            rod(m,f"deck_tow_cable_{side}_{i}","Tracks",
                (x0,hull_height(x0,z0)+.014,z0),
                (x0,hull_height(x0,z1)+.014,z1),.012)
        for i,z in enumerate((.97,.30,-.44,-1.17)):
            # Circular flush access caps on the sloping hull shoulders.
            points = [(side*.835+.049*math.cos(j*math.tau/12),
                       z+.049*math.sin(j*math.tau/12)) for j in range(12)]
            surface_plate(m,f"deck_access_cap_{side}_{i}","HullFittings",points,hull_height)
    # Rear lower plate, central towing assembly and spare wheel between drums.
    # Follow the approved side profile's rising rear belly, not a vertical
    # plate hanging down behind the track approach.
    m.loft("rear_lower_plate", "HullFittings",
           [[(x,y,z+offset) for x,y,z in
             ((-.58,.26,-1.60),(.58,.26,-1.60),(.70,.65,-2.13),(-.70,.65,-2.13))]
            for offset in (0,-.025)])
    m.loft("rear_tow_mount", "HullFittings",
           [[(x,y,z+offset) for x,y,z in
             ((-.064,.32,-1.68),(.064,.32,-1.68),(.064,.49,-1.92),(-.064,.49,-1.92))]
            for offset in (0,-.10)])
    m.cylinder("rear_tow_eye", "Tracks",(0,.45,-1.99),.036,.02,axis=2,sides=16)
    m.cylinder("rear_spare_wheel", "Tracks",(-.09,.69,-2.64),.127,.075,axis=2)
    m.cylinder("rear_spare_hub", "HullFittings",(-.09,.69,-2.688),.061,.035,axis=2,sides=16)
    m.box("rear_stowage_box", "HullFittings",(.09,.67,-2.63),(.225,.92,-2.40))
    # Central driver's hatch/periscope and readable lower-front stiffeners.
    m.box("driver_hatch", "Base",(-.17,.74,1.53),(.17,.80,1.86))
    m.box("driver_periscope", "Tracks",(-.12,.80,1.60),(.12,.845,1.67))
    for i in range(7):
        x = -.54+i*.18
        m.loft(f"front_plate_rib_{i}", "Base",
               [[(xx,y,z+offset) for xx,y,z in
                 ((x-.012,.30,1.557),(x+.012,.30,1.557),
                  (x+.012,.51,1.812),(x-.012,.51,1.812))] for offset in (0,.014)])
    m.cylinder("turret_ring", "Turret", (0,.95+TURRET_RISE/2,0),
               .69,.08+TURRET_RISE,axis=1,sides=32)
    # Measured turret silhouette: long low roof, sloped cheeks, near-vertical
    # rear bustle. Cross-sections also taper its width rather than box extrusion.
    m.loft("turret_armour", "Turret",
           [[(-w,*profile(px,bottom)),(w,*profile(px,bottom)),
             (roof_w,*profile(px,top)),(-roof_w,*profile(px,top))]
            for px,top,bottom,w,roof_w in
            ((222,98,101,.74,.70),(289,62,106,.86,.76),
             (365,57,104,.87,.79),(466,68,94,.84,.78))])
    # Broad sloped cheeks flank a central gun opening. Flat applique panels
    # follow the cheek slope rather than standing vertically like boxes.
    for side in (-1,1):
        x = side*.54
        m.loft(f"cheek_panel_{side}", "TurretDark",
               [[(xx,y,z+offset) for xx,y,z in
                 ((x-.17,1.07,1.09),(x+.17,1.07,1.09),
                  (x+.17,1.26,.737),(x-.17,1.26,.737))] for offset in (0,.012)])
        m.box(f"smoke_rack_{side}", "Turret",(x-.13,.95,1.20),(x+.13,1.025,1.30))
        for i in range(5):
            xx = x+(i%3-1)*.075
            yy = 1.035+(i//3)*.07
            m.tube(f"smoke_launcher_{side}_{i}", "TurretDark",(xx,yy,1.30),.031,.15,
                   (side*(.25+.12*(i%3)),.55,1))
        # Rear turret grille panels frame the broad, almost vertical bustle.
        m.box(f"turret_rear_grille_{side}", "TurretDark",(x-.235,1.005,-1.428),(x+.235,1.25,-1.412))
        for i in range(4):
            y = 1.03+i*.056
            m.box(f"turret_rear_louvre_{side}_{i}", "Turret",(x-.222,y,-1.44),(x+.222,y+.017,-1.425))
        # Low long bins define the turret footprint from above.
        m.box(f"turret_side_bin_{side}", "Turret",(side*.79-.045,1.07,-1.24),
              (side*.79+.045,1.25,-.30))
    m.cylinder("commander_cupola", "Turret",(-.33,1.42,-.12),.235,.095,axis=1)
    m.cylinder("commander_hatch", "Turret",(-.33,1.477,-.12),.19,.020,axis=1)
    for i in range(8):
        a = i*math.tau/8
        m.tube(f"cupola_periscope_{i}", "TurretDark",
               (-.33+.223*math.cos(a),1.43,-.12+.223*math.sin(a)),.025,.038,
               (math.cos(a),0,math.sin(a)),sides=4)
    m.box("commander_sight", "Turret",(-.48,1.32,.24),(-.25,1.605,.42))
    m.box("commander_sight_glass", "TurretDark",(-.452,1.445,.422),(-.277,1.574,.434))
    m.box("gunner_sight", "Turret",(.24,1.19,1.03),(.48,1.35,1.30))
    m.box("gunner_sight_glass", "TurretDark",(.269,1.247,1.303),(.452,1.321,1.315))
    roof_details(m)
    m.cylinder("roof_sensor", "Turret",(-.18,1.485,-.39),.025,.21,axis=1,sides=12)
    for x,z in ((-.52,-.75),(.52,-.98)):
        m.cylinder(f"aerial_base_{x}", "Turret",(x,1.37,z),.035,.12,axis=1,sides=12)
        m.cylinder(f"aerial_{x}", "Turret",(x,1.72,z),.006,.62,axis=1,sides=8)
    # Barrel material includes mantlet, so all geometry elevates/recoils together.
    bore_y = profile(0,84)[0]
    m.box("mantlet", "Barrel",(-.19,bore_y-.105,.80),(.19,bore_y+.105,1.19))
    for name,z0,z1,r in (("breech_sleeve",1.12,1.38,.09),
                         ("thermal_sleeve",1.38,2.49,.064),
                         ("fume_extractor",2.49,2.91,.088),
                         ("forward_tube",2.91,3.69,.059)):
        m.cylinder(name,"Barrel",(0,bore_y,(z0+z1)/2),r,z1-z0,axis=2)
    # Annular lip and recessed bore, not a solid painted muzzle disc.
    n = 24
    muzzle_z = profile(8,0)[1]
    vertices = [(r*math.cos(i*math.tau/n),bore_y+r*math.sin(i*math.tau/n),z)
                for r,z in ((.067,3.68),(.067,muzzle_z),(.043,muzzle_z),(.043,3.70))
                for i in range(n)]
    faces = []
    for i in range(n):
        j = (i+1)%n
        for a,b in ((0,1),(1,2),(2,3)):
            faces.append([a*n+i,a*n+j,b*n+j,b*n+i])
    faces.append(list(range(3*n,4*n)))
    m.mesh("open_muzzle", "Barrel", vertices, faces)
    return m


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output-dir", type=Path,
                        default=Path(__file__).resolve().parents[1]/"assets/models")
    args = parser.parse_args()
    model = build()
    args.output_dir.mkdir(parents=True, exist_ok=True)
    (args.output_dir/"challenger2.obj").write_text("\n".join(model.lines)+"\n")
    (args.output_dir/"challenger2.mtl").write_text(
        "# Runtime replaces these preview colours with the existing tiled materials.\n" +
        "\n".join(f"newmtl {name}\nKd {colour}\nKs 0.1 0.1 0.1\nNs 24\n"
                    for name,colour in (("Base","0.28 0.32 0.18"),("HullFittings","0.28 0.32 0.18"),
                                        ("Turret","0.28 0.32 0.18"),("TurretDark","0.10 0.11 0.10"),
                                        ("Tracks","0.10 0.11 0.10"),("Barrel","0.19 0.22 0.15"))))
    print(f"Authored {model.count} vertices / {model.triangles} triangles in {args.output_dir}")


if __name__ == "__main__":
    main()
